---
# file: roles/postgresql_server/tasks/main.yml

- name: add PostgreSQL repository
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main'
  tags:
      - postgres

- name: add PostgreSQL key
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc
  tags:
      - postgres

- name: install PostgreSQL (common from raring repo) via apt
  apt: name={{ item }} default_release=raring update-cache=true
  with_items:
    - postgresql-common

- name: install PostgreSQL via apt
  apt: name={{ item }}
  with_items:
    - postgresql-9.1
    - postgresql-contrib-9.1
    - python-psycopg2
    - libpostgresql-jdbc-java
  tags:
    - postgres