language: python
python: '2.6'
addons:
  firefox: "25.0.1"
install:
  - pip install ansible
  - sudo pip install dopy
before_script:
  - ansible-playbook -i localhost --extra-vars "api_key_password=$DO_API_KEY client_id=$DO_CLIENT_ID" do_cluster.yml
  - sleep 5 # give Digital Ocean some time to fully provision the nodes
  - eval `ssh-agent`
  - chmod 400 travis.ssh && ssh-add travis.ssh
  - ansible-playbook -i hosts --extra-vars "authorized_rsa_key=$(cat travis.ssh.pub)" -u root bootstrap/bootstrap.yml
script:
  - ansible-playbook -i hosts --extra-vars "accelerate=false" site.yml
after_success:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - wget http://download.slimerjs.org/v0.9/0.9.0rc1/slimerjs-0.9.0rc1.zip
  - unzip slimerjs-0.9.0rc1.zip
  - mv slimerjs-0.9.0rc1 ./slimerjs
  - ./after_success.sh
after_script:
  - sudo /etc/rc6.d/K10do_destroy.sh
env:
  global:
    - ANSIBLE_HOST_KEY_CHECKING=False
    - ANSIBLE_SSH_ARGS="-o ForwardAgent=yes"
    - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0 PATH=$TRAVIS_BUILD_DIR/slimerjs:$PATH
    - secure: "YBnTdEJ6U6i5no2eRlVC5dsqvSmYqULG+zWyTk2KqWGGMCza3RFi0wUueK3NuN+tl4Ijzf26Kma7wqdjkort0UrfxiH2xd4DWv3LvWz5vpKFP4GaSQGcd5zokHAJJ5hs0JgKY5jwGfoNHcnL16oUJEtptfLqTjGKRIHS+Ye1LmQ="
    - secure: "DmsCmxwGBWVnYV6CDuCiJsATk85eFUr/Zs7BeYWjlKvAQz4Np9GTDECe3rE1KAA42PZrbvyAdWD31Np9QF0zj8Aq6poCvZ0c0Mib2bRi3eOP8tPL6EUggAl125UkoAZzxtgRWvILZfeRGhBzYsRX9C7/UtA8F8Ij0hXknkgdY48="
    - secure: "e1CgM7pcNr5P8aOlLAthEO1PmE9Fy7yxveH09ARvOICkupkNjdM3CAvjQAI5xbhD/ExEjqlRbGHb7LMTrPyLbNehTDTcxcD4gWeNte18hE9A+4foGFOUzyWa7+2X5j6LndLec8EAxV87eI2uX5oO4VSggg3CXhuR084ETg/4ah8="
    - GH_USER_NAME: analytically
    - GH_PROJECT_NAME: hadoop-ansible
    - GIT_AUTHOR_NAME: "TravisCI"
    - GIT_AUTHOR_EMAIL: "noreply@travis-ci.org"