---
# file: roles/elasticsearch_curator/tasks/main.yml

- name: install python-pip via apt
  apt: pkg=python-pip
  tags: elasticsearch_curator

- name: clone the elasticsearch-curator repo to /var/lib/logstash-index-cleaner
  git: repo=https://github.com/elasticsearch/curator.git dest=/var/lib/elasticsearch-curator update=true
  tags: elasticsearch_curator

- name: pip install -r requirements.txt
  shell: chdir=/var/lib/elasticsearch-curator pip install -r requirements.txt
  tags: elasticsearch_curator

- name: install the elasticsearch-curator crontab at /etc/cron.d/elasticsearch-curator
  template: src=elasticsearch-curator.cron.d dest=/etc/cron.d/elasticsearch-curator owner=root group=root mode=644
  tags: elasticsearch_curator