---
# file: roles/common/tasks/main.yml

- name: upgrade all safe packages
  apt: upgrade=safe

- name: configure /etc/security/limits.conf with high max file descriptors (soft/hard)
  template: src=limits.conf dest=/etc/security/limits.conf mode=0644

- name: configure /etc/pam.d/common-session and /etc/pam.d/common-session-noninteractive with pam_limits.so
  lineinfile: name={{ item }} regexp='pam_limits.so' line='session required pam_limits.so'
  with_items:
    - /etc/pam.d/common-session
    - /etc/pam.d/common-session-noninteractive

- name: install commonly used packages via apt
  apt: pkg={{ item }}
  with_items:
    - checkinstall
    - htop
    - sshguard
    - curl
    - net-tools
    - liblzo2-dev
    - zip
    - intel-microcode

- name: create the hosts file for all machines
  template: src=hosts dest=/etc/hosts

- name: configure rsyslog with the imfile module
  template: src=rsyslog.conf dest=/etc/rsyslog.d/30-imfile.conf owner=root group=root mode=0644
  tags: rsyslog
  notify:
    - restart rsyslog

- name: install NTP
  apt: pkg=ntp
  tags: ntp

- name: configure NTP in /etc/ntp.conf
  template: src=ntp.conf dest=/etc/ntp.conf
  notify:
    - restart ntp
  tags: ntp

- name: make sure NTP is running and enabled
  service: name=ntp state=running enabled=yes
  tags: ntp