---
# file: roles/elasticsearch/tasks/main.yml

- name: install Elasticsearch
  shell: creates=/usr/share/elasticsearch/bin/elasticsearch chdir=/tmp wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.0.0.deb && dpkg -i elasticsearch-1.0.0.deb
  tags: elasticsearch

- name: install Elasticsearch marvel plugin
  shell: creates=/usr/share/elasticsearch/plugins/marvel chdir=/usr/share/elasticsearch/bin ./plugin -install elasticsearch/marvel/latest
  tags: elasticsearch