---
# file: roles/aggregated_links_common/tasks/main.yml
# see https://help.ubuntu.com/community/UbuntuBonding

- name: install ifenslave-2.6
  apt: pkg=ifenslave-2.6
  tags: bonding

- name: configure bonding kernel module
  lineinfile: dest=/etc/modules regexp="bonding" line=bonding
  tags: bonding