---
# file: roles/mysql_server/tasks/main.yml

- name: predefine MySQL root passwd
  shell: executable=/bin/bash debconf-set-selections <<< "mysql-server-5.5 mysql-server/root_password password hive_{{ site_name }}"

- name: predefine MySQL root passwd confirm
  shell: executable=/bin/bash debconf-set-selections <<< "mysql-server-5.5 mysql-server/root_password_again password hive_{{ site_name }}"

- name: install MySQL via apt
  apt: name={{ item }}
  with_items:
    - mysql-server-5.5
    - libmysql-java
    - python-mysqldb
  tags:
    - mysql

- name: create MySQL db 'metastore'
  mysql_db: name=metastore state=present
            login_user=root login_password=hive_{{ site_name }}
  tags:
    - mysql
    - hive

- name: init Hive metastore schema
  shell: mysql -uroot -phive_{{ site_name }} metastore < /usr/lib/hive/scripts/metastore/upgrade/mysql/hive-schema-0.10.0.mysql.sql
  tags:
    - mysql
    - hive

- name: add and grant MySQL user 'hiveuser'
  mysql_user: name=hiveuser host=localhost password=hive_{{ site_name }} priv=metastore.*:ALL state=present
              login_user=root login_password=hive_{{ site_name }}
  tags:
    - mysql
    - hive